# Generated by Codex on 2026-01-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banco_questoes", "0002_planos_assinaturas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_ref", models.CharField(db_index=True, max_length=64, unique=True)),
                ("valor_centavos", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("PENDING", "Pendente"), ("PAID", "Pago"), ("EXPIRED", "Expirado"), ("FAILED", "Falhou")], default="PENDING", max_length=20)),
                ("pix_id", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("pix_qrcode_base64", models.TextField(blank=True, default="")),
                ("pix_br_code", models.TextField(blank=True, default="")),
                ("payload_criacao", models.JSONField(blank=True, default=dict)),
                ("payload_webhook", models.JSONField(blank=True, default=dict)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("plano_destino", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="billings", to="banco_questoes.plano")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="billings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("tipo", models.CharField(max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                ("status_processamento", models.CharField(default="PENDING", max_length=40)),
            ],
        ),
        migrations.AddIndex(
            model_name="billing",
            index=models.Index(fields=["usuario", "status"], name="payments_bi_usuario_e46b3b_idx"),
        ),
        migrations.AddIndex(
            model_name="billing",
            index=models.Index(fields=["pix_id"], name="payments_bi_pix_id_7207b1_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["tipo"], name="payments_we_tipo_d9cb60_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["event_id"], name="payments_we_event__8d2ed5_idx"),
        ),
    ]
