# Generated by Django 6.0 on 2026-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billing',
            new_name='payments_bi_usuario_579b6b_idx',
            old_name='payments_bi_usuario_e46b3b_idx',
        ),
        migrations.RenameIndex(
            model_name='billing',
            new_name='payments_bi_pix_id_2a4c08_idx',
            old_name='payments_bi_pix_id_7207b1_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='payments_we_tipo_5e55de_idx',
            old_name='payments_we_tipo_d9cb60_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='payments_we_event_i_aaa1d5_idx',
            old_name='payments_we_event__8d2ed5_idx',
        ),
    ]
