# Generated by Django 6.0 on 2026-02-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostilaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo_pdf', models.FileField(upload_to='apostila_cnh/')),
                ('ativo', models.BooleanField(default=False)),
                ('total_paginas', models.PositiveIntegerField(default=0)),
                ('idioma', models.CharField(default='pt-BR', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ativo', 'titulo'],
                'indexes': [models.Index(fields=['ativo'], name='apost_doc_ativo_idx'), models.Index(fields=['slug'], name='apost_doc_slug_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='apost_unq_documento_ativo_true')],
            },
        ),
        migrations.CreateModel(
            name='ApostilaPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.PositiveIntegerField()),
                ('texto', models.TextField(blank=True, default='')),
                ('texto_normalizado', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='apostila_cnh.apostiladocumento')),
            ],
            options={
                'ordering': ['documento', 'numero_pagina'],
                'indexes': [models.Index(fields=['documento', 'numero_pagina'], name='apost_pag_doc_num_idx'), models.Index(fields=['documento'], name='apost_pag_doc_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'numero_pagina'), name='apost_unq_doc_numero_pagina')],
            },
        ),
        migrations.CreateModel(
            name='ApostilaProgressoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_pagina_lida', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='apostila_cnh.apostiladocumento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostila_cnh_progressos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['usuario', 'documento'], name='apost_prog_user_doc_idx'), models.Index(fields=['documento'], name='apost_prog_doc_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'documento'), name='apost_unq_usuario_documento_progresso')],
            },
        ),
    ]
