# Generated by Django 6.0 on 2026-02-23 08:31

import apostila_cnh.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostila_cnh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostiladocumento',
            name='arquivo_pdf',
            field=models.FileField(storage=apostila_cnh.storage.PrivateApostilaStorage(), upload_to='apostila_cnh/'),
        ),
    ]
