# Generated by Django 6.0 on 2026-02-12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banco_questoes", "0004_app_access_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaRespostaPreferenciaUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tempo_entre_questoes_segundos", models.PositiveSmallIntegerField(default=12)),
                ("modo_automatico_ativo", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="perguntas_respostas_preferencia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia Perguntas e Respostas",
                "verbose_name_plural": "Preferencias Perguntas e Respostas",
            },
        ),
        migrations.CreateModel(
            name="PerguntaRespostaEstudo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contexto_hash", models.CharField(db_index=True, max_length=64)),
                ("contexto_json", models.JSONField(blank=True, default=dict)),
                ("primeiro_estudo_em", models.DateTimeField()),
                ("ultimo_estudo_em", models.DateTimeField()),
                ("vezes_estudada", models.PositiveIntegerField(default=1)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="perguntas_respostas_estudos",
                        to="banco_questoes.questao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="perguntas_respostas_estudos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico Perguntas e Respostas",
                "verbose_name_plural": "Historico Perguntas e Respostas",
                "indexes": [
                    models.Index(
                        fields=["usuario", "contexto_hash", "ultimo_estudo_em"],
                        name="pr_estudo_user_ctx_last_idx",
                    ),
                    models.Index(fields=["usuario", "questao"], name="pr_estudo_user_questao_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "questao", "contexto_hash"),
                        name="uniq_pr_estudo_usuario_questao_contexto",
                    ),
                ],
            },
        ),
    ]
