"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv


# -----------------------------------------------------------------------------
# Paths & .env
# -----------------------------------------------------------------------------
# settings.py está em: <BASE_DIR>/config/settings.py
# e o manage.py / .env estão em: <BASE_DIR>/
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega .env ANTES de qualquer os.getenv()
load_dotenv(dotenv_path=BASE_DIR / ".env", override=True)


def env_bool(key: str, default: str = "0") -> bool:
    return os.getenv(key, default).strip() in {"1", "true", "True", "yes", "YES"}


def env_required(key: str) -> str:
    val = os.getenv(key)
    if val is None or val == "":
        raise RuntimeError(f"Variável de ambiente ausente/vazia: {key}. Verifique o .env em {BASE_DIR}")
    return val


# -----------------------------------------------------------------------------
# Core
# -----------------------------------------------------------------------------
SECRET_KEY = env_required("DJANGO_SECRET_KEY")
DEBUG = env_bool("DJANGO_DEBUG", "0")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")


# -----------------------------------------------------------------------------
# Applications
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "banco_questoes",
    "menu",
    "perguntas_respostas",
    "apostila_cnh",
    "simulacao_prova",
    "manual_pratico",
    "aprenda_jogando",
    "oraculo",
    "aprova_plus",
    "payments",
]


# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -----------------------------------------------------------------------------
# URLs / WSGI
# -----------------------------------------------------------------------------
ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"


# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # templates globais (ex.: BASE_DIR/templates/simulado/config.html)
        "DIRS": [BASE_DIR / "templates"],
        # templates dentro dos apps (ex.: banco_questoes/templates/...)
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
            ],
        },
    },
]


# -----------------------------------------------------------------------------
# Database (PostgreSQL)
# -----------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env_required("DB_NAME"),
        "USER": env_required("DB_USER"),
        "PASSWORD": env_required("DB_PASSWORD"),
        # default seguro para evitar localhost/IPv6
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
    }
}


# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# Auth / Session
# -----------------------------------------------------------------------------
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
SESSION_COOKIE_AGE = 20 * 24 * 60 * 60  # o primeiri número: 20 dias
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Toggle para cooldown de cadastro (IP + device)
REGISTER_COOLDOWN_ENABLED = env_bool("REGISTER_COOLDOWN_ENABLED", "1")
# Flags de rollout do controle de acesso por app (Fase 2)
APP_ACCESS_V2_ENABLED = env_bool("APP_ACCESS_V2_ENABLED", "0")
APP_ACCESS_DUAL_WRITE = env_bool("APP_ACCESS_DUAL_WRITE", "0")


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------
LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "pt-br")
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "America/Sao_Paulo")
USE_I18N = True
USE_TZ = True


# -----------------------------------------------------------------------------
# Static files
# -----------------------------------------------------------------------------
STATIC_URL = "static/"

# Em desenvolvimento, se BASE_DIR/static existir, ele é usado como diretório de
# estáticos "do projeto".
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Em produção, o collectstatic irá copiar tudo para STATIC_ROOT.
# Pensando na estrutura da VPS:
#   /srv/simulado_digital/app    -> BASE_DIR
#   /srv/simulado_digital/shared -> BASE_DIR.parent / "shared"
STATIC_ROOT = BASE_DIR.parent / "shared" / "staticfiles"


# -----------------------------------------------------------------------------
# Segurança / Proxy / Cloudflare
# -----------------------------------------------------------------------------
# Redirect para HTTPS controlado por env (Cloudflare faz o SSL)
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", "0")

# CSRF_TRUSTED_ORIGINS pode vir do .env (separado por vírgula)
_raw_csrf_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
if _raw_csrf_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _raw_csrf_origins.split(",") if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -----------------------------------------------------------------------------
# Payments / AbacatePay
# -----------------------------------------------------------------------------
ABACATEPAY_API_URL = os.getenv("ABACATEPAY_API_URL", "https://api.abacatepay.com")
ABACATEPAY_API_TOKEN = os.getenv("ABACATEPAY_API_TOKEN", "")
ABACATEPAY_WEBHOOK_SECRET = os.getenv("ABACATEPAY_WEBHOOK_SECRET", "")
ABACATEPAY_WEBHOOK_PUBLIC_HMAC_KEY = os.getenv("ABACATEPAY_WEBHOOK_PUBLIC_HMAC_KEY", "")
ABACATEPAY_WEBHOOK_SIGNATURE_HEADER = os.getenv(
    "ABACATEPAY_WEBHOOK_SIGNATURE_HEADER",
    "X-Webhook-Signature",
)


# -----------------------------------------------------------------------------
# local_settings.py (overrides por ambiente)
# -----------------------------------------------------------------------------
# Permite que cada servidor/ambiente faça overrides sem mexer neste arquivo
try:
    from .local_settings import *  # type: ignore[unused-ignore]
except ImportError:
    # Em ambientes sem local_settings.py (ex.: CI), segue apenas com as configs acima.
    pass
