# Generated by Django 6.0 on 2025-12-17 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CursoModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveSmallIntegerField(help_text='Ordem de exibição no curso (1..N).')),
                ('nome', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('CONTEUDO', 'Conteúdo'), ('SIMULADO', 'Simulado / Teste')], db_index=True, default='CONTEUDO', max_length=20)),
                ('pagina_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pagina_fim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='banco_questoes.curso')),
            ],
            options={
                'ordering': ['curso__nome', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('arquivo_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano', 'titulo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('arquivo_hash', ''), _negated=True), fields=('arquivo_hash',), name='uniq_documento_por_hash_quando_preenchido')],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_no_modulo', models.PositiveSmallIntegerField()),
                ('dificuldade', models.CharField(blank=True, choices=[('FACIL', 'Fácil'), ('INTERMEDIARIO', 'Intermediário'), ('DIFICIL', 'Difícil')], max_length=20, null=True)),
                ('enunciado', models.TextField()),
                ('comentario', models.TextField(blank=True, default='')),
                ('codigo_placa', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('imagem_arquivo', models.CharField(blank=True, default='', max_length=255)),
                ('pagina_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pagina_fim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_block', models.TextField(blank=True, default='')),
                ('import_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco_questoes.curso')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco_questoes.documento')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco_questoes.cursomodulo')),
            ],
            options={
                'ordering': ['curso__nome', 'modulo__ordem', 'numero_no_modulo'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('is_correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='banco_questoes.questao')),
            ],
            options={
                'ordering': ['questao', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='cursomodulo',
            index=models.Index(fields=['curso', 'categoria', 'ordem'], name='banco_quest_curso_i_2abc26_idx'),
        ),
        migrations.AddConstraint(
            model_name='cursomodulo',
            constraint=models.UniqueConstraint(fields=('curso', 'ordem'), name='uniq_modulo_ordem_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='cursomodulo',
            constraint=models.UniqueConstraint(fields=('curso', 'nome'), name='uniq_modulo_nome_por_curso'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['curso', 'modulo', 'numero_no_modulo'], name='banco_quest_curso_i_198ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['codigo_placa'], name='banco_quest_codigo__a933b0_idx'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['dificuldade'], name='banco_quest_dificul_c7864b_idx'),
        ),
        migrations.AddConstraint(
            model_name='questao',
            constraint=models.UniqueConstraint(fields=('documento', 'modulo', 'numero_no_modulo'), name='uniq_questao_por_documento_modulo_numero'),
        ),
        migrations.AddConstraint(
            model_name='questao',
            constraint=models.UniqueConstraint(condition=models.Q(('import_hash', ''), _negated=True), fields=('import_hash',), name='uniq_questao_import_hash_quando_preenchido'),
        ),
        migrations.AddIndex(
            model_name='alternativa',
            index=models.Index(fields=['questao', 'is_correta'], name='banco_quest_questao_3cda5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('questao', 'ordem'), name='uniq_ordem_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correta', True)), fields=('questao',), name='uniq_uma_correta_por_questao'),
        ),
    ]
