# Generated by Codex on 2026-01-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_plano_free(apps, schema_editor):
    Plano = apps.get_model("banco_questoes", "Plano")
    if Plano.objects.filter(nome__iexact="Free").exists():
        return
    Plano.objects.create(
        nome="Free",
        limite_qtd=3,
        limite_periodo="DIARIO",
        validade_dias=None,
        ciclo_cobranca="NAO_RECORRENTE",
        preco=0,
        ativo=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("banco_questoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plano",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("limite_qtd", models.PositiveIntegerField(blank=True, null=True)),
                ("limite_periodo", models.CharField(blank=True, choices=[("DIARIO", "Diario"), ("SEMANAL", "Semanal"), ("MENSAL", "Mensal"), ("ANUAL", "Anual")], max_length=20, null=True)),
                ("validade_dias", models.PositiveIntegerField(blank=True, null=True)),
                ("ciclo_cobranca", models.CharField(choices=[("MENSAL", "Mensal"), ("ANUAL", "Anual"), ("NAO_RECORRENTE", "Nao recorrente")], default="NAO_RECORRENTE", max_length=20)),
                ("preco", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Assinatura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_plano_snapshot", models.CharField(blank=True, default="", max_length=120)),
                ("limite_qtd_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("limite_periodo_snapshot", models.CharField(blank=True, choices=[("DIARIO", "Diario"), ("SEMANAL", "Semanal"), ("MENSAL", "Mensal"), ("ANUAL", "Anual")], max_length=20, null=True)),
                ("validade_dias_snapshot", models.PositiveIntegerField(blank=True, null=True)),
                ("ciclo_cobranca_snapshot", models.CharField(choices=[("MENSAL", "Mensal"), ("ANUAL", "Anual"), ("NAO_RECORRENTE", "Nao recorrente")], default="NAO_RECORRENTE", max_length=20)),
                ("preco_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("status", models.CharField(choices=[("ATIVO", "Ativo"), ("EXPIRADO", "Expirado"), ("PAUSADO", "Pausado")], default="ATIVO", max_length=20)),
                ("inicio", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("plano", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assinaturas", to="banco_questoes.plano")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assinaturas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SimuladoUso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("janela_inicio", models.DateTimeField()),
                ("janela_fim", models.DateTimeField()),
                ("contador", models.PositiveIntegerField(default=0)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="simulado_uso", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="EventoAuditoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(max_length=60)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=64)),
                ("contexto_json", models.JSONField(blank=True, default=dict)),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="eventos_auditoria", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="assinatura",
            index=models.Index(fields=["usuario", "status"], name="banco_quest_usuario_3c7fa4_idx"),
        ),
        migrations.AddConstraint(
            model_name="simuladouso",
            constraint=models.UniqueConstraint(fields=("usuario", "janela_inicio", "janela_fim"), name="uniq_uso_por_usuario_janela"),
        ),
        migrations.AddIndex(
            model_name="simuladouso",
            index=models.Index(fields=["usuario", "janela_fim"], name="banco_quest_usuario_5a13d1_idx"),
        ),
        migrations.AddIndex(
            model_name="eventoauditoria",
            index=models.Index(fields=["tipo"], name="banco_quest_tipo_0b3536_idx"),
        ),
        migrations.AddIndex(
            model_name="eventoauditoria",
            index=models.Index(fields=["timestamp"], name="banco_quest_timesta_8d9db4_idx"),
        ),
        migrations.AddIndex(
            model_name="eventoauditoria",
            index=models.Index(fields=["ip"], name="banco_quest_ip_1d3e5f_idx"),
        ),
        migrations.RunPython(seed_plano_free, migrations.RunPython.noop),
    ]
