# Generated by Django 6.0 on 2026-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0002_planos_assinaturas'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assinatura',
            new_name='banco_quest_usuario_dbeb40_idx',
            old_name='banco_quest_usuario_3c7fa4_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='banco_quest_tipo_c2212f_idx',
            old_name='banco_quest_tipo_0b3536_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='banco_quest_timesta_2a2216_idx',
            old_name='banco_quest_timesta_8d9db4_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='banco_quest_ip_faed94_idx',
            old_name='banco_quest_ip_1d3e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='simuladouso',
            new_name='banco_quest_usuario_be46c3_idx',
            old_name='banco_quest_usuario_5a13d1_idx',
        ),
    ]
