# Generated by Codex on 2026-02-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_questoes", "0003_rename_banco_quest_usuario_3c7fa4_idx_banco_quest_usuario_dbeb40_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppModulo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("nome", models.CharField(max_length=120)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem_menu", models.PositiveSmallIntegerField(default=0)),
                ("icone_path", models.CharField(blank=True, default="", max_length=255)),
                ("rota_nome", models.CharField(blank=True, default="", max_length=120)),
                ("em_construcao", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ordem_menu", "nome"],
            },
        ),
        migrations.CreateModel(
            name="PlanoPermissaoApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permitido", models.BooleanField(default=False)),
                ("limite_qtd", models.PositiveIntegerField(blank=True, null=True)),
                ("limite_periodo", models.CharField(blank=True, choices=[("DIARIO", "Diario"), ("SEMANAL", "Semanal"), ("MENSAL", "Mensal"), ("ANUAL", "Anual")], max_length=20, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("app_modulo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permissoes_planos", to="banco_questoes.appmodulo")),
                ("plano", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permissoes_apps", to="banco_questoes.plano")),
            ],
            options={
                "ordering": ["plano__nome", "app_modulo__ordem_menu", "app_modulo__nome"],
            },
        ),
        migrations.CreateModel(
            name="UsoAppJanela",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("janela_inicio", models.DateTimeField()),
                ("janela_fim", models.DateTimeField()),
                ("contador", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("app_modulo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usos_janela", to="banco_questoes.appmodulo")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="uso_apps_janela", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="planopermissaoapp",
            constraint=models.UniqueConstraint(fields=("plano", "app_modulo"), name="uniq_plano_permissao_app"),
        ),
        migrations.AddConstraint(
            model_name="usoappjanela",
            constraint=models.UniqueConstraint(fields=("usuario", "app_modulo", "janela_inicio", "janela_fim"), name="uniq_usoapp_usuario_janela"),
        ),
        migrations.AddIndex(
            model_name="appmodulo",
            index=models.Index(fields=["ativo", "ordem_menu"], name="bq_appmod_ativo_ordem_idx"),
        ),
        migrations.AddIndex(
            model_name="planopermissaoapp",
            index=models.Index(fields=["plano", "permitido"], name="bq_planoapp_plano_perm_idx"),
        ),
        migrations.AddIndex(
            model_name="planopermissaoapp",
            index=models.Index(fields=["app_modulo"], name="bq_planoapp_app_idx"),
        ),
        migrations.AddIndex(
            model_name="usoappjanela",
            index=models.Index(fields=["usuario", "app_modulo", "janela_fim"], name="bq_usoapp_user_app_fim_idx"),
        ),
    ]

