# Generated by Codex on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_questoes", "0004_app_access_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfertaUpgradeUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("campanha_slug", models.SlugField(max_length=120)),
                ("ciclo", models.PositiveIntegerField(default=1)),
                ("janela_inicio", models.DateTimeField()),
                ("janela_fim", models.DateTimeField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ofertas_upgrade", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="ofertaupgradeusuario",
            constraint=models.UniqueConstraint(fields=("usuario", "campanha_slug"), name="uniq_oferta_upgrade_usuario_campanha"),
        ),
        migrations.AddIndex(
            model_name="ofertaupgradeusuario",
            index=models.Index(fields=["campanha_slug", "janela_fim"], name="bq_oferta_slug_fim_idx"),
        ),
    ]
