# Generated by Django 6.0 on 2026-03-02 11:19

import banco_questoes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0005_ofertaupgradeusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCadastroPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=banco_questoes.models._generate_convite_token, max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio_vigencia', models.DateTimeField(blank=True, null=True)),
                ('fim_vigencia', models.DateTimeField(blank=True, null=True)),
                ('limite_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_realizados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_cadastro', to='banco_questoes.plano')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['ativo', 'fim_vigencia'], name='bq_convite_ativo_fim_idx')],
            },
        ),
    ]
