# Generated by Django 6.0 on 2026-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0006_convitecadastroplano'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitecadastroplano',
            name='permitir_fallback_free',
            field=models.BooleanField(default=True),
        ),
    ]
