# Generated by Django 6.0 on 2026-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0007_convitecadastroplano_permitir_fallback_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitecadastroplano',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convitecadastroplano',
            name='nome_representante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
