# Generated by Django 6.0 on 2026-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_questoes', '0008_convitecadastroplano_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='permite_upgrade_pix',
            field=models.BooleanField(default=False),
        ),
    ]
